wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1657701684
    t:
      1:
      - 2
      - 3
      - 5
      - 30
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 30
      - 53
      - 55
      4: 3.9.12
      5: 0.12.20
      8:
      - 3
      - 5
